SELECT DISTINCT  RD_FILIAL, 
		RD_MAT,
		RA_NOME,
		RA_CATFUNC,
	    RA_CATEG,
		SUM(BASECALCULO) BASECALCULO, 
		SUM(EXCEDENTE)EXCEDENTE,
		SUM(SEG_CONT_EMPREGAVULSO)SEG_CONT_EMPREGAVULSO,
		SUM(SEG_CONT_INDIVIDUAL)SEG_CONT_INDIVIDUAL,
		SUM(EMPRESA_EMPREGAVULSOS)EMPRESA_EMPREGAVULSOS,
		SUM(EMPRESA_CONTRINDIVIDUAIS)EMPRESA_CONTRINDIVIDUAIS,
		SUM(RAT) RAT,
		SUM(RETENCAO) RETENCAO,
		SUM(SFAMILIA) SFAMILIA,
		SUM(SMATERNIDADE) SMATERNIDADE,
		SUM(OENTIDADES) OENTIDADES,
		SUM(SEG_CONT_EMPREGAVULSO + SEG_CONT_INDIVIDUAL + EMPRESA_EMPREGAVULSOS + 
		EMPRESA_CONTRINDIVIDUAIS + RAT - RETENCAO - SFAMILIA - SMATERNIDADE) VLR_RECOLHER_PREV_SOCIAL,
		SUM(SEG_CONT_EMPREGAVULSO + SEG_CONT_INDIVIDUAL + EMPRESA_EMPREGAVULSOS + 
		EMPRESA_CONTRINDIVIDUAIS + RAT - RETENCAO - SFAMILIA - SMATERNIDADE + OENTIDADES) TOTAL_RECOLHER
FROM (SELECT DISTINCT	RD_FILIAL, 
		RD_MAT,
		RA_NOME,
		RA_CATFUNC,
		RA_CATEG,
		CASE WHEN RV_CODFOL iN ('0013','0019','0221') THEN CAST(RD_VALOR as decimal(6, 2)) ELSE 0 END BASECALCULO,
		CASE WHEN RV_CODFOL iN ('0014','0020') THEN CAST(RD_VALOR as decimal(6, 2)) ELSE 0 END EXCEDENTE,
		CASE WHEN RV_CODFOL IN('0064','0070','0065') and RD_PROCES = '00001' THEN CAST(RD_VALOR as decimal(6, 2)) ELSE 0 END SEG_CONT_EMPREGAVULSO,
		CASE WHEN RD_PROCES = '00003'  THEN CASE WHEN RV_CODFOL <> '0221' THEN CAST(RD_VALOR as decimal(6, 2)) END ELSE 0 END SEG_CONT_INDIVIDUAL,
		CASE WHEN RV_CODFOL IN('0148') THEN CASE WHEN RD_PROCES = '00001' THEN CAST(RD_VALOR as decimal(6, 2)) END ELSE 0 END EMPRESA_EMPREGAVULSOS,
		CASE WHEN RV_CODFOL IN('0148') THEN CASE WHEN RD_PROCES = '00003' THEN CAST(RD_VALOR as decimal(6, 2)) END ELSE 0 END EMPRESA_CONTRINDIVIDUAIS,
		CASE WHEN RV_CODFOL IN('0150') THEN CAST(RD_VALOR as decimal(6, 2)) ELSE 0 END RAT,
		ISNULL(CASE WHEN SUBSTRING(RCC_CONTEU,34,1) = 'S' THEN CASE WHEN RV_CODFOL IN('0148') THEN CAST(RD_VALOR as decimal(6, 2)) END ELSE 0 END ,0)RETENCAO,
		CASE WHEN RV_CODFOL IN('0034') THEN CAST(RD_VALOR as decimal(6, 2)) ELSE 0 END SFAMILIA,
		CASE WHEN RV_CODFOL IN('0040','0407') THEN CAST(RD_VALOR as decimal(6, 2)) ELSE 0 END SMATERNIDADE,
		CASE WHEN RV_CODFOL IN('0149','0204','0184','0185','0186','0187','0188','0189') THEN CAST(RD_VALOR as decimal(6, 2)) ELSE 0 END OENTIDADES 
FROM SRD$P!{CODIGO_EMPRESA}
LEFT JOIN SRV$P!{CODIGO_EMPRESA} ON
(RV_FILIAL = RD_FILIAL OR LEFT(RD_FILIAL, 2) = RV_FILIAL OR RV_FILIAL = '')  AND RD_PD = RV_COD 
AND RD_PERIODO = '$P!{ANO}$P!{MES}'
LEFT JOIN SRA$P!{CODIGO_EMPRESA} ON
(RA_FILIAL = RD_FILIAL OR LEFT(RA_FILIAL, 2) = RD_FILIAL OR RD_FILIAL = '') AND RD_MAT =RA_MAT
LEFT JOIN RCC$P!{CODIGO_EMPRESA} ON
(RD_FILIAL = RCC_FIL OR LEFT(RD_FILIAL, 2) = RCC_FIL OR RCC_FIL = '') AND RCC_CODIGO ='S037'
WHERE RD_PD in (SELECT RV_COD FROM SRV$P!{CODIGO_EMPRESA} WHERE RV_CODFOL IN
('0013','0019','0221', '0014','0020', '0064','0070','0065','0150', '0034','0040','0407','0149','0204'
,'0184','0185','0186','0187','0188','0189' , '0148') )
AND RD_PERIODO = '$P!{ANO}$P!{MES}'
AND SRA$P!{CODIGO_EMPRESA}.D_E_L_E_T_ = '' OR SRA$P!{CODIGO_EMPRESA}.D_E_L_E_T_ IS NULL
AND RD_VALOR <> 0 )X
WHERE RA_NOME <> ''
GROUP BY
	    X.RD_FILIAL, 
		X.RD_MAT,
		X.RA_NOME,
		X.RA_CATFUNC,
	    X.RA_CATEG
ORDER BY RA_NOME
