SELECT R8_FILIAL CODIGO_FILIAL,
    APS_DESC_FILIAL FILIAL,
    R8_MAT MATRICULA,
    RA_NOME NOME,
    CTT_CUSTO CODIGO_CENTRO_CUSTO,
    CTT_DESC01 CENTRO_DE_CUSTO,
    RJ_FUNCAO CODIGO_FUNCAO,
    RJ_DESC FUNCAO,
    R8_TIPOAFA CODIGO_AFASTAMENTO,
    RCM_DESCRI TIPO_DE_AFASTAMENTO,
    R8_CID CID,
    R8_CRMMED CRM,
    R8_UFCRM UF_CRM,
    dbo.stod(R8_DATAINI) DATA_INICIO,
    dbo.stod(R8_DATAFIM) DATA_FIM
FROM SR8$P!{CODIGO_EMPRESA} SR8
    JOIN API_SIGAMAT ON R8_FILIAL = APS_COD_FILIAL AND APS_COD_EMPRESA = '$P!{CODIGO_EMPRESA}'
    JOIN SRA$P!{CODIGO_EMPRESA} SRA ON (R8_MAT = RA_MAT AND R8_FILIAL = RA_FILIAL AND SRA.D_E_L_E_T_='')
    JOIN SRJ$P!{CODIGO_EMPRESA} SRJ ON (RA_FILIAL = RJ_FILIAL OR LEFT(RA_FILIAL, 2) = RJ_FILIAL OR RJ_FILIAL = '') AND RA_CODFUNC = RJ_FUNCAO AND SRJ.D_E_L_E_T_ = ''
    JOIN CTT$P!{CODIGO_EMPRESA} CTT ON (RA_FILIAL = CTT_FILIAL OR LEFT(RA_FILIAL, 2) = CTT_FILIAL OR CTT_FILIAL = '') AND RA_CC = CTT_CUSTO AND CTT.D_E_L_E_T_ = ''
    JOIN RCM$P!{CODIGO_EMPRESA} RCM ON (RA_FILIAL = RCM_FILIAL OR LEFT(RA_FILIAL, 2) = RCM_FILIAL OR RCM_FILIAL = '') AND RCM_TIPO = R8_TIPOAFA AND RCM.D_E_L_E_T_=''
WHERE SR8.D_E_L_E_T_=''
    AND (RA_DEMISSA = '' OR LEFT(RA_DEMISSA, 6) >= '$P!{ANO}$P!{MES}')
    AND R8_FILIAL= '$P!{CODIGO_FILIAL}'
ORDER BY R8_FILIAL,
         RA_NOME,
         RA_MAT,
         R8_DATAINI
