SELECT RA_FILIAL FILIAL,
       RA_MAT MATRICULA,
       RA_NOME NOME,
       RA_CODFUNC CODIGO_FUNCAO,
       RJ_DESC FUNCAO,
       RA_CC CODIGO_CENTRO_CUSTO,
       CTT_DESC01 CENTRO_DE_CUSTO,
       RA_NATURAL NATURALIDADE,
       RA_ESTCIVI ESTADO_CIVIL,
       RA_SEXO SEXO,
       X5_DESCRI ESCOLARIDADE,
       dbo.calculaidade(RA_NASC) IDADE,
       dbo.stod(RA_ADMISSA) ADMISSAO,
       dbo.calculaidade(RA_ADMISSA) TEMPO_DE_EMPRESA,
       RA_SALARIO AS SALARIO
FROM SRA$P!{CODIGO_EMPRESA} SRA
JOIN CTT$P!{CODIGO_EMPRESA} CTT ON (RA_FILIAL = CTT_FILIAL OR LEFT(RA_FILIAL, 2) = CTT_FILIAL OR CTT_FILIAL = '') AND RA_CC = CTT_CUSTO AND CTT.D_E_L_E_T_ = ''
JOIN SRJ$P!{CODIGO_EMPRESA} SRJ ON (RA_FILIAL = RJ_FILIAL OR LEFT(RA_FILIAL, 2) = RJ_FILIAL OR RJ_FILIAL = '') AND RA_CODFUNC = RJ_FUNCAO AND SRJ.D_E_L_E_T_ = ''
JOIN SX5$P!{CODIGO_EMPRESA} GRINRAI ON (RA_FILIAL = GRINRAI.X5_FILIAL OR LEFT(RA_FILIAL, 2) = GRINRAI.X5_FILIAL OR GRINRAI.X5_FILIAL = '') AND RA_GRINRAI = GRINRAI.X5_CHAVE AND GRINRAI.X5_TABELA = '26' AND GRINRAI.D_E_L_E_T_ = ''
WHERE SRA.D_E_L_E_T_ = ''
  AND RA_DEMISSA = ''
  AND RA_PROCES='00001'
  AND RA_FILIAL LIKE (IIF( 1>'$P!{CONSOLIDADO}', '$P!{CODIGO_FILIAL}', '%%'));
ORDER BY RA_FILIAL,
         RA_NOME
